"""
JiraClient — creates JIRA tickets with full analysis in the description.

The full analysis (root cause, fixes, debugging steps, etc.) is embedded
directly in the ticket DESCRIPTION so it always appears in the creation email.
A plain-text comment is also added as a backup.
"""
from __future__ import annotations

import json
from datetime import datetime, timezone

import requests as req

from app.config import settings
from app.models import AnalyzedEvent, JiraTicketInfo
from app.utils.logger import get_logger

logger = get_logger(__name__)


# ── ADF helpers ────────────────────────────────────────────────────────────────

def _txt(text: str) -> dict:
    return {"type": "text", "text": text}


def _bold(text: str) -> dict:
    return {"type": "text", "text": text, "marks": [{"type": "strong"}]}


def _heading(text: str, level: int = 2) -> dict:
    return {
        "type": "heading",
        "attrs": {"level": level},
        "content": [_txt(text)],
    }


def _paragraph(*parts) -> dict:
    return {"type": "paragraph", "content": list(parts)}


def _rule() -> dict:
    return {"type": "rule"}


def _numbered_list(items: list[str]) -> list[dict]:
    """Returns an orderedList node only if items is non-empty."""
    if not items:
        return [_paragraph(_txt("None identified."))]
    list_items = []
    for item in items:
        list_items.append({
            "type": "listItem",
            "content": [_paragraph(_txt(str(item)))],
        })
    return [{"type": "orderedList", "content": list_items}]


def _code_block(text: str) -> dict:
    return {
        "type": "codeBlock",
        "attrs": {"language": "json"},
        "content": [_txt(text)],
    }


def _build_description(event: AnalyzedEvent) -> dict:
    """
    Build a rich ADF document with all analysis sections.
    This goes directly into the ticket description so it appears in emails.
    """
    msg = (event.error.log_entry.get("message")
           or event.error.log_entry.get("msg", "Unknown error"))
    sev = event.step2.severity.upper()
    conf = f"{event.step2.confidence_score:.0%}"
    service = event.error.log_entry.get("service", "unknown")
    detected = event.error.detected_at[:19].replace("T", " ")

    content = []

    # ── Header ──
    content.append(_paragraph(
        _bold("Service: "), _txt(service),
        _txt("   |   "),
        _bold("Severity: "), _txt(sev),
        _txt("   |   "),
        _bold("Confidence: "), _txt(conf),
        _txt("   |   "),
        _bold("Detected: "), _txt(detected),
    ))
    content.append(_rule())

    # ── Root Cause ──
    content.append(_heading("Root Cause", 2))
    content.append(_paragraph(_txt(event.step2.root_cause)))

    # ── Technical Explanation ──
    content.append(_heading("Technical Explanation", 2))
    content.append(_paragraph(_txt(event.step2.technical_explanation)))

    # ── Debugging Steps ──
    content.append(_heading("Debugging Steps", 2))
    content.extend(_numbered_list(event.step2.debugging_steps))

    # ── Possible Solutions ──
    content.append(_heading("Possible Solutions", 2))
    content.extend(_numbered_list(event.step2.possible_fixes))

    # ── Possible Failures / Affected Components ──
    content.append(_heading("Possible Failures & Affected Components", 2))
    affected = event.step2.affected_components
    if affected:
        content.extend(_numbered_list(affected))
    else:
        content.append(_paragraph(_txt("No specific components identified.")))

    # ── Suspected Functions ──
    content.append(_heading("Suspected Functions (Step 1)", 2))
    fns = event.step1.suspected_functions
    if fns:
        content.append(_paragraph(_txt(", ".join(fns))))
    else:
        content.append(_paragraph(_txt("None identified.")))
    content.append(_paragraph(_bold("Reasoning: "), _txt(event.step1.reasoning)))

    # ── Raw Log Entry ──
    content.append(_heading("Raw Log Entry", 2))
    content.append(_code_block(json.dumps(event.error.log_entry, indent=2)))

    # ── Footer ──
    content.append(_rule())
    content.append(_paragraph(
        _txt("Generated by "),
        _bold("Debug Pipeline"),
        _txt(f" | Event ID: {event.id}"),
    ))

    return {"type": "doc", "version": 1, "content": content}


class JiraClient:

    def __init__(self) -> None:
        self._auth    = (settings.jira_email, settings.jira_api_token)
        self._base    = settings.jira_base_url.rstrip("/")
        self._proj    = settings.jira_project_key
        self._headers = {"Content-Type": "application/json", "Accept": "application/json"}

    # ── Public ─────────────────────────────────────────────────────────────────

    async def create_ticket(self, event: AnalyzedEvent) -> JiraTicketInfo:
        import asyncio
        loop = asyncio.get_event_loop()
        return await loop.run_in_executor(None, self._create_ticket_sync, event)

    async def test_connection(self) -> dict:
        import asyncio
        loop = asyncio.get_event_loop()
        return await loop.run_in_executor(None, self._test_connection_sync)

    # ── Sync implementation ────────────────────────────────────────────────────

    def _create_ticket_sync(self, event: AnalyzedEvent) -> JiraTicketInfo:
        summary     = self._build_summary(event)
        priority    = self._severity_to_priority(event.step2.severity)
        description = _build_description(event)

        # Three attempts — progressively simpler — description included in all
        attempts = [
            # Attempt 1: Bug + priority + description
            {
                "project":     {"key": self._proj},
                "summary":     summary,
                "issuetype":   {"name": "Bug"},
                "priority":    {"name": priority},
                "description": description,
            },
            # Attempt 2: Bug without priority
            {
                "project":     {"key": self._proj},
                "summary":     summary,
                "issuetype":   {"name": "Bug"},
                "description": description,
            },
            # Attempt 3: Task (exists in every project)
            {
                "project":     {"key": self._proj},
                "summary":     summary,
                "issuetype":   {"name": "Task"},
                "description": description,
            },
        ]

        last_error = ""
        for i, fields in enumerate(attempts, 1):
            payload = {"fields": fields}
            logger.info(
                "JIRA attempt %d — issuetype=%s priority=%s",
                i,
                fields.get("issuetype", {}).get("name"),
                fields.get("priority", {}).get("name", "—"),
            )
            try:
                resp = req.post(
                    f"{self._base}/rest/api/3/issue",
                    json=payload,
                    auth=self._auth,
                    headers=self._headers,
                    timeout=30,
                )
                logger.info("JIRA attempt %d → HTTP %d", i, resp.status_code)

                if resp.status_code in (200, 201):
                    body       = resp.json()
                    ticket_id  = body["key"]
                    ticket_url = f"{self._base}/browse/{ticket_id}"
                    logger.info("JIRA ticket created: %s  %s", ticket_id, ticket_url)

                    # Plain-text comment as a backup / audit trail
                    self._add_plain_comment(ticket_id, event)

                    return JiraTicketInfo(
                        ticket_id=ticket_id,
                        ticket_url=ticket_url,
                        created_at=datetime.now(timezone.utc).isoformat(),
                    )

                # If description caused a 400, retry without it
                if resp.status_code == 400 and "description" in fields:
                    logger.warning(
                        "Attempt %d failed (400) — retrying without description: %s",
                        i, resp.text[:200],
                    )
                    fields_no_desc = {k: v for k, v in fields.items() if k != "description"}
                    resp2 = req.post(
                        f"{self._base}/rest/api/3/issue",
                        json={"fields": fields_no_desc},
                        auth=self._auth,
                        headers=self._headers,
                        timeout=30,
                    )
                    if resp2.status_code in (200, 201):
                        body       = resp2.json()
                        ticket_id  = body["key"]
                        ticket_url = f"{self._base}/browse/{ticket_id}"
                        logger.info(
                            "JIRA ticket created (no-desc fallback): %s  %s",
                            ticket_id, ticket_url,
                        )
                        # Description failed in body — put everything in comment
                        self._add_plain_comment(ticket_id, event)
                        return JiraTicketInfo(
                            ticket_id=ticket_id,
                            ticket_url=ticket_url,
                            created_at=datetime.now(timezone.utc).isoformat(),
                        )

                last_error = f"HTTP {resp.status_code}: {resp.text[:300]}"

            except req.exceptions.RequestException as exc:
                last_error = str(exc)
                logger.error("JIRA request error (attempt %d): %s", i, exc)

        raise RuntimeError(
            f"JIRA ticket creation failed after {len(attempts)} attempts. "
            f"Last error: {last_error}"
        )

    def _add_plain_comment(self, ticket_id: str, event: AnalyzedEvent) -> None:
        """Plain-text comment — backup/audit trail."""
        msg  = event.error.log_entry.get("message") or event.error.log_entry.get("msg", "")
        fns  = ", ".join(event.step1.suspected_functions) or "None identified"

        lines = [
            "=== Debug Pipeline — Automated Analysis ===",
            "",
            f"Error     : {msg}",
            f"Service   : {event.error.log_entry.get('service', 'unknown')}",
            f"Severity  : {event.step2.severity.upper()}",
            f"Confidence: {event.step2.confidence_score:.0%}",
            f"Detected  : {event.error.detected_at[:19]}",
            "",
            "--- Root Cause ---",
            event.step2.root_cause,
            "",
            "--- Technical Explanation ---",
            event.step2.technical_explanation,
            "",
            "--- Debugging Steps ---",
        ]
        for i, s in enumerate(event.step2.debugging_steps, 1):
            lines.append(f"  {i}. {s}")

        lines += ["", "--- Possible Solutions ---"]
        for i, f in enumerate(event.step2.possible_fixes, 1):
            lines.append(f"  {i}. {f}")

        affected = ", ".join(event.step2.affected_components) or "N/A"
        lines += [
            "",
            "--- Possible Failures & Affected Components ---",
            affected,
            "",
            "--- Suspected Functions (Step 1) ---",
            fns,
            f"Reasoning: {event.step1.reasoning}",
            "",
            "--- Raw Log Entry ---",
            json.dumps(event.error.log_entry, indent=2),
            "",
            f"Event ID: {event.id}",
        ]

        body = {
            "body": {
                "type": "doc",
                "version": 1,
                "content": [{
                    "type": "paragraph",
                    "content": [{"type": "text", "text": "\n".join(lines)}],
                }],
            }
        }
        try:
            resp = req.post(
                f"{self._base}/rest/api/3/issue/{ticket_id}/comment",
                json=body,
                auth=self._auth,
                headers=self._headers,
                timeout=30,
            )
            if resp.status_code in (200, 201):
                logger.info("Comment added to %s", ticket_id)
            else:
                logger.warning("Comment failed [%d]: %s", resp.status_code, resp.text[:200])
        except Exception as exc:
            logger.warning("Could not add comment to %s: %s", ticket_id, exc)

    def _test_connection_sync(self) -> dict:
        result: dict = {"ok": False}
        try:
            me = req.get(
                f"{self._base}/rest/api/3/myself",
                auth=self._auth, headers=self._headers, timeout=30,
            )
            if me.status_code != 200:
                result["error"] = f"Auth failed [{me.status_code}]: {me.text[:200]}"
                return result
            me_data = me.json()
            result["logged_in_as"] = me_data.get("displayName") or me_data.get("emailAddress")

            proj = req.get(
                f"{self._base}/rest/api/3/project/{self._proj}",
                auth=self._auth, headers=self._headers, timeout=30,
            )
            if proj.status_code != 200:
                result["error"] = (
                    f"Project '{self._proj}' not found "
                    f"[{proj.status_code}]: {proj.text[:200]}"
                )
                return result
            proj_data = proj.json()
            result["project_name"] = proj_data.get("name")
            result["issue_types"]  = [it["name"] for it in proj_data.get("issueTypes", [])]

            pri = req.get(
                f"{self._base}/rest/api/3/priority",
                auth=self._auth, headers=self._headers, timeout=30,
            )
            if pri.status_code == 200:
                result["priorities"] = [p["name"] for p in pri.json()]

            result["ok"] = True
        except req.exceptions.RequestException as exc:
            result["error"] = f"Network error: {exc}"
        return result

    # ── Helpers ────────────────────────────────────────────────────────────────

    @staticmethod
    def _build_summary(event: AnalyzedEvent) -> str:
        msg = (event.error.log_entry.get("message")
               or event.error.log_entry.get("msg") or "Unknown error")
        return f"[{event.step2.severity.upper()}] {str(msg)[:110]}"

    @staticmethod
    def _severity_to_priority(severity: str) -> str:
        return {
            "critical": "Highest",
            "high":     "High",
            "medium":   "Medium",
            "low":      "Low",
        }.get(severity, "Medium")
